apiVersion: v1
kind: Pod
metadata:
  name: ubuntu03-taint-master
  labels:
    app: ubuntu03-taint-master
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "k8s-default", "name":"VN-01"}'
  }
spec:
  nodeSelector:
    "kubernetes.io/hostname": "contrail-node1"
  containers:
    - name: ubuntu03-taint-master
      image: ubuntu-upstart