apiVersion: v1
kind: Pod
metadata:
  name: ubuntu02
  labels:
    app: ubuntu02
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "k8s-default", "name":"VN-01"}'
  }
spec:
  containers:
    - name: ubuntu02
      image: ubuntu-upstart